# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_logo', models.CharField(max_length=400)),
                ('movie_date', models.CharField(max_length=5)),
                ('movie_genre', models.CharField(max_length=300)),
            ],
        ),
    ]
